plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'com.cosmical'
version '1.0.0'

repositories {
    mavenCentral() // Usiamo solo il server centrale ufficiale, il più sicuro al mondo
}

dependencies {
    // Nuova libreria di login aggiornata e stabile presente direttamente su MavenCentral
    implementation 'net.kyori:adventure-api:4.14.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}

shadowJar {
    archiveClassifier.set('completo')
}
