plugins {
    id 'application'
}

group 'com.cosmical'
version '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // 🌟 La libreria ufficiale Microsoft per fare il login sicuro con la finestrella del browser
    implementation 'com.microsoft.azure:msal4j:1.14.3'
    implementation 'org.slf4j:slf4j-simple:2.0.7'
}

application {
    mainClass = 'com.cosmical.launcher.MainLauncher'
}

jar {
    manifest {
        attributes(
            'Main-Class': 'com.cosmical.launcher.MainLauncher'
        )
    }
}
