plugins {
    id 'application' // Il plugin ufficiale di Gradle per creare i programmi .jar eseguibili
}

group 'com.cosmical'
version '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.json:json:20231013' // Libreria standard sicura per decodificare il login Microsoft
}

application {
    // Diciamo a Gradle quale file deve cliccare per primo all'avvio
    mainClass = 'com.cosmical.launcher.MainLauncher'
}

jar {
    manifest {
        attributes(
            'Main-Class': 'com.cosmical.launcher.MainLauncher'
        )
    }
}
